Correct ServerRegion Strings
us_east, us_west, etc (with '_') causes 400 BAD REQUEST exception:

Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 294, in on_message
    await client.edit_server( cur_serv.me, region=req_reg )
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 2381, in edit_server
    yield from self.http.edit_server(server.id, **fields)
  File "/usr/lib/python3.6/site-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

Replacing '_' with '-' causes the call to return successfully and correctly update the region.